spring.application.name=auth-service
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/observaflow

jwt.secret=7yvRz8XpW8bN4mQ9K2tV5zC8xN1qW3zR6vT8yU0wX2m=
jwt.expiration-ms=3600000
