spring.application.name=auth-service
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/observaflow

server.port=8081

jwt.secret=TohteykvoZlJW7Bt9y5pKden+1ehr4p2L0xHS5yYIvLj0Pz7KEtLOKDXsMFCNX1E
jwt.expiration-ms=3600000
