spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: ingest-service
          uri: http://localhost:8082
          predicates:
            - Path=/ingest/**

        - id: processor-service
          uri: http://localhost:8083
          predicates:
            - Path=/processor/**

        - id: alert-service
          uri: http://localhost:8084
          predicates:
            - Path=/alert/**

        - id: websocket-service
          uri: http://localhost:8086
          predicates:
            - Path=/ws/**

        - id: query-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/query/**

server:
  port: 8080

jwt:
  secret: TohteykvoZlJW7Bt9y5pKden+1ehr4p2L0xHS5yYIvLj0Pz7KEtLOKDXsMFCNX1E
